version: 2
registries:
  github-octocat:
    type: git
    url: https://github.com
    username: tue-robotics-robots
    password: ${{secrets.DEPENDABOT_TOKEN}}
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    registries:
      - github-octocat
    schedule:
      interval: "daily"
