# This travis configuration has ssh keys added to recurse submodules from private gitlab repository
# Steps to enable ssh support with travis and gitlab are as follows:
#
# On the local PC
# 1. Generate a ssh keypair to be used with CI
#    ```
#    mkdir -p ~/travis
#    ssh-keygen -t rsa -b 4096 -N "" -f ~/travis/deploy_key
#    ```
#
# 2. Add the ssh key to travis
#    ```
#    gem install travis
#    cd <REPOSITORY>
#    travis encrypt-file ~/travis/deploy_key --pro --add
#    ```
#    The last command will automatically generate and set two environment variables `encrypted_<STRING>_key` and
#    `encrypted_<STRING>_iv`in the repository settings of travis. They are not to be removed.
#
# 3. Change the value of `-out` option in `before_install: - openssl` to `./deploy_key`
#
# 4. Commit the updated .travis.yml file and the generated file `deploy_key.enc`
#
# 5. Append the following lines to .travis.yml under `before_install`
#    ```
#    - eval "$(ssh-agent -s)"
#    - chmod 600 ./deploy_key
#    - ssh-add ./deploy_key
#
# On GITLAB
# 6. In the repository Settings > CI/CD > Deploy Keys, add the public key from the file ~/travis/deploy_key.pub

os: linux
dist: xenial
language: shell
addons:
  ssh_known_hosts: gitlab.com
  apt:
    packages:
      - yamllint
git:
  submodules: false

before_install:
  - openssl aes-256-cbc -K $encrypted_2fc69c4133c3_key -iv $encrypted_2fc69c4133c3_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - ssh-add ./deploy_key

install:
  - git submodule update --init --recursive

script:
  - bash -c 'shopt -s globstar; shellcheck **/*.bash **/*.sh **/setup'
  - bash -c 'find ./ -iname '*.yaml' -or -iname '*.yml' | xargs yamllint'
