os: linux
dist: bionic
language: shell
addons:
  ssh_known_hosts: gitlab.com
git:
  submodules: false

before_install:
  - openssl aes-256-cbc -K $encrypted_2fc69c4133c3_key -iv $encrypted_2fc69c4133c3_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - ssh-add ./deploy_key

install:
  - git submodule update --init --recursive

before_script:
  - sudo apt-get install python3-pip
  - pip3 install --user --upgrade setuptools wheel
  - pip3 install --user --upgrade yamllint

script:
  - bash -c 'shopt -s globstar; shellcheck ./**/*.bash ./**/*.sh ./**/setup'
  - bash -c 'find ./ -iname '*.yaml' -or -iname '*.yml' | xargs yamllint'
  # Check if either both 'set -e' and 'set +e' are used or none
  # yamllint disable rule:indentation
  - |
      bash -c '
      shopt -s globstar
      bad_files=""
      files=$(echo ./**/*.bash ./**/*.sh ./**/setup)
      for file in $files
      do
          if ! grep -Eqz ".*set -e.*set \+e.*" "$file" && (grep -Eqz "set -e" "$file" || grep -Eqz "set \+e" "$file")
          then
              bad_files=${bad_files:+${bad_files} }$file
          fi
      done

      if [ -n "$bad_files" ]
      then
          echo -e "\033[38;5;1mFollowing file(s) have only \"set -e\" or \"set +e\", use both or none:\033[0m"
          for bad_file in $bad_files
          do
              echo -e "\033[38;5;1m   $bad_file\033[0m"
          done
          exit 1
      fi
      '
  # yamllint enable rule:indentation
